language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm test
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  skip_cleanup: true
  email: ta7sudan@gmail.com
  api_key:
    secure: dkgpP7Y41p+ROM+Z64YwUA/1pDDK6ezmUlBZon1eP28oCxZwiYHXa6OGVcNHi3Uu/5NWsgXXkLpAbPNxEs+LHtJT326jyo8+843tW30miAyXj9V+VGj4h9Ve9nMct40/CDfl5mlYYAkCN/QCDd24+LFqRcbswL30YeQ8iXIAplOh1oSLRw5kuVRitnMQyAmiePrNHuZmDQYh8fcDus0vXQnRV00TyQO6v0E8gP96sozyGKVs8SQNsE9RQo80MPgY1UL4kvIkUbBN1DgBCKCP33dydUXen92KMRFhbm+JGo9irGqUdeZPHAAVrziMVfxCwxgBtuqfYQ5fbo0Hh3cfj7qxbOqmtkHfzVRmQdKXS8p7Alt1xUySWBBhGFP3fSq/t5Ba9DiOri8hRIbmGYXo7NR2eHUwKt/VDSHh1CDOMDQ5RuR/eX6IMe6nbDJggmyQJ9Bv+7mKxJ4b0tEnm65X8pODI13Er9aAO5IucMzILb8QMnFxlw3BOX6/eMjaAbMu1K0yDF828MPfh0euAJSzVDA60NCxZ1qEnD8FcNK4JSAjQ5t91KhT8WXQ2fIoXOIRlQ6kVc8p5EMUjpbz/EUCHHkCK6dfCFrcDCBhFxheNFiG+eWYfZhEPZQsfcvuhWlFr0FF4HXkSpSc6xL00WX9+2y7ThUlreMnSGjptbgaA/Y=
  on:
    tags: true
    repo: ta7sudan/tinyjx
    branch: dev
