language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm test
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  skip_cleanup: true
  email: ta7sudan@gmail.com
  tag: next
  api_key:
    secure: mr16MqsnVA+gZdIS1uj85eDgxxuP/N4AtrTjnR9YU9y/ivNn99ZML1R9JSKc/XV/0Ku0a+lPuN/rQfBB658d4nqUDWP54YmhhH5FQMO1IU44zG+lFFJ4rqjsGWWLsZLXE6AD3tFnUBhKj7UoOTdqqOyYU9tJCdpnR70vKpOrKQV1ALFtOxs+/OX0po97kviEPAv8nzaba0x0xv3wbL+pk3IvVUldmtaLLfI4lCnudOKGJsbmAmE27SYW6J+CWzQLyO03NMTa7EjvhTWrEqI2Xb00mEx7vGrES2HElYqV9+WP4f61K7CyuzW0Y/JbtG1FZnlmTjVYXu5kte5tgMOo1JT+9OLKfkkHFigU+CeM82gfWw0CGByH2f1bCiHD14mdgTKgbqAQ6o7IdKZNYQyH9s61PMH6YM4a8lbtraPX8UTCL/noBEmgNtqprtoqAfFc/68kdpXLm2aI2wBUGZ703Wh9DZkhBVUXba5u2K35dBGVMJ1ZfBTGT9KF0hoZ4eG2cVGxFHKoNq4zv08CpXC9vtW2vPPIf/kq+p30BFuTtX4Td+0dEh7Wf/AXYoQRWP0z8np24vrsJNX4liPqT4DNWvE72quhqMjNbPXRF0woERyKD2e5gwEZGIdJHmBMTLu8FTkMpYzkk/xo4gLXWWMgsComUaguhOvrHU7Q4T1ge8Y=
  on:
    tags: true
    repo: ta7sudan/tinyjx
    branch: next
